# Generated by Django 4.2.13 on 2024-07-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_vendorhandles_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorhandles",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.instrumentgroupmaster",
            ),
        ),
    ]
