# Generated by Django 4.2.13 on 2024-07-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_alter_vendorhandles_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shedtools",
            name="shed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app1.sheddetails",
            ),
        ),
    ]
