# Generated by Django 4.2.13 on 2024-07-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_shedtools_shed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shedtools",
            name="shed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="app1.sheddetails",
            ),
        ),
    ]
