# Generated by Django 4.2.13 on 2024-07-29 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app1", "0005_alter_shedtools_shed"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheduser",
            name="shed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.sheddetails",
            ),
        ),
        migrations.AlterField(
            model_name="sheduser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
