# Generated by Django 4.2.13 on 2024-07-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_sheduser_shed_alter_sheduser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheduser",
            name="shed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.sheddetails"
            ),
        ),
    ]
